In [1]:
import pandas as pd

In [5]:
pokemon = pd.read_csv("pokemon.csv")

In [25]:
pokemon.shape

(800, 12)

In [27]:
pokemon.head(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [29]:
pokemon.columns

Index(['Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [21]:
#Confrontiamolo con l'indice messo automaticamente da Pandas: combaciano?
#No, in quanto per alcune varianti dello stesso Pokemon il numero di Pokedex non cambia
pokemon = pokemon.set_index("#")

In [89]:
colonne = ['Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']
leggendari = pokemon.loc[:,"Legendary"]
pokemon.loc[leggendari,colonne]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [107]:
erba1 = pokemon.loc[:,"Type 1"]== "Grass"
erba2 = pokemon.loc[:,"Type 2"]== "Grass"
filtro_erba = erba1 | erba2
leggendari_erba = leggendari & filtro_erba
pokemon.loc[leggendari_erba,colonne]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
492,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True

In [111]:
fuoco1 = pokemon.loc[:,"Type 1"]== "Fire"
fuoco2 = pokemon.loc[:,"Type 2"]== "Fire"
ghiaccio1 = pokemon.loc[:,"Type 1"]== "Ice"
ghiaccio2 = pokemon.loc[:,"Type 2"]== "Ice"
filtro_fuoco = fuoco1 | fuoco2
filtro_ghiaccio = ghiaccio1 | ghiaccio2
filtro_fuoco_o_ghiaccio = filtro_fuoco | filtro_ghiaccio
leggendari_ghiaccio_o_fuoco = leggendari & filtro_fuoco_o_ghiaccio
pokemon.loc[leggendari_ghiaccio_o_fuoco,colonne]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
378,Regice,Ice,NaN,580,80,50,100,100,200,50,3,True
383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
494,Victini,Psychic,Fire,600,100,100,100,100,100,100,5,True
643,Reshiram,Dragon,Fire,680,100,120,100,150,120,90,5,True
646,Kyurem,Dragon,Ice,660,125,130,90,130,90,95,5,True
646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True
646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [115]:
pokemon.sort_values("Name")

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True